---
# - name: CCNP ENARSI Lab Manual 2.1.2
#   hosts: routers
#   gather_facts: False
#   strategy: free
#   roles:
#   - enable_interfaces
#   - rtr_interfaces
#   - dhcp_config

- name: CCNP ENARSI Lab Manual 2.1.2
  hosts: D1
  gather_facts: False
  strategy: free
  roles:
  # - enable_interfaces
  # - vlans
  - l2_interfaces
