---
- name: CCNP ENARSI Lab Manual 2.1.2
  hosts: cisco
  gather_facts: False
  # strategy: free
  tasks:
    - name: run show version on remote devices
      cisco.ios.ios_command:
        commands: show version

    # - name: VIEW ALL ANSIBLE FACT KEYS
    #   debug:
    #     var: ansible_net_interfaces