---
- name: CCNP ENARSI Lab Manual Routers
  hosts: RTR1
  gather_facts: False
  strategy: free
  vars_files:
    - ./labs/{{ lab }}/{{ inventory_hostname }}.yaml
  roles:
  - enable_interfaces
  - rtr_interfaces
  - dhcp_config

- name: CCNP ENARSI Lab Manual Switches
  hosts: switches
  gather_facts: False
  strategy: free
  vars_files:
    - ./labs/{{ lab }}/{{ inventory_hostname }}.yaml
  roles:
  - role: enable_interfaces
  - role: vlans
    when: vlans is defined
  - role: sw_interfaces