---
- name: Checking for valid lab definition
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Check that lab is defined
      assert:
        that: lab is defined
        fail_msg: "no lab defined, please add extra vars defining lab variable"
        # Example ansible-playbook destroy.yaml -e lab=01_2.1.2

- name: Reset devices
  hosts: cisco
  gather_facts: False
  strategy: free
  vars_files:
    - ./labs/{{ lab }}/{{ inventory_hostname }}.yaml
  roles:
  - destroy_lab
  # - reset_reload # Not working for IOSv Routers
  tasks:

    # - name: configure register for reboot #weird bug for IOL images?
    #   cisco.ios.ios_config:
    #     lines:
    #     - config-register 0x2102

    - name: save config before reload
      cisco.ios.ios_config:
        save_when: always

- name: reset switch layer 2 stuffs
  hosts: switches
  gather_facts: False
  strategy: free
  vars_files:
    - ./labs/{{ lab }}/{{ inventory_hostname }}.yaml
  roles:
  - destroy_vlans
  - reset_reload