---
- name: Checking for valid lab definition
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Check that lab is defined
      assert:
        that: lab is defined
        fail_msg: "no lab defined, please add extra vars defining lab variable"
        # Example ansible-playbook destroy.yaml -e 'lab=01_2.1.2'

- name: Reset devices
  hosts: cisco
  gather_facts: False
  strategy: free
  vars_files:
    - ./labs/{{ lab }}/{{ inventory_hostname }}.yaml
  tasks:

    - name: delete sub interfaces
      cisco.ios.ios_config:
        lines:
        - no interface {{ item.name }}
      loop: "{{ sub_interfaces }}"
      loop_control:
        label: "{{ item.name }}"
      when: sub_interfaces is defined

    - name: delete loopbacks
      cisco.ios.ios_config:
        lines:
        - no interface {{ item.name }}
      loop: "{{ interfaces }}"
      loop_control:
        label: "{{ item.name }}"
      when:  "'Loopback' in item.name"

    - name: default interfaces
      cisco.ios.ios_config:
        lines:
        - default interface {{ item.name }}
      loop: "{{ interfaces }}"
      loop_control:
        label: "{{ item.name }}"
      when: "interfaces is defined and 'Loopback' not in item.name"

    - name: delete eigrp process
      cisco.ios.ios_config:
        lines:
        - no router eigrp {{ destroy.eigrp.as }}
      when: destroy.eigrp.as is defined

    - name: delete key chains
      cisco.ios.ios_config:
        lines:
        - no key chain {{ item.name }}
      loop: "{{ destroy.key_chains }}"
      loop_control:
        label: "{{ item.name }}"
      when: destroy.key_chains is defined

    - name: delete named standard acls
      cisco.ios.ios_config:
        lines:
        - no ip access-list standard {{ item.name }}
      loop: "{{ destroy.acl.named.standard }}"
      when: destroy.acl.named.standard is defined

    # - name: configure register for reboot #weird bug for IOL images?
    #   cisco.ios.ios_config:
    #     lines:
    #     - config-register 0x2102

    - name: configure reset banner
      cisco.ios.ios_banner:
        banner: motd
        text: |
          {{ inventory_hostname }} has been reset
        state: present

    - name: save config before reload
      cisco.ios.ios_config:
        save_when: always

# IOSv for routers needs to be worked on, reload issue
#     - name: reload device
#       ansible.netcommon.cli_command: 
#         command: reload
#         prompt: 
#           - confirm
#         answer: 
#           - y

#     - name: reset the connection 
#       meta: reset_connection

#     - name: wait for network device to come back up
#       wait_for_connection:
#         delay: 15

- name: reset switch layer 2 stuffs
  hosts: switches
  gather_facts: False
  strategy: free
  vars_files:
    - ./labs/{{ lab }}/{{ inventory_hostname }}.yaml
  tasks:

    - name: delete switch VLANs
      cisco.ios.ios_config:
        lines:
        - no vlan {{ item.id }}
      loop: "{{ vlans }}"
      when: vlans is defined

    - name: save config before reload
      cisco.ios.ios_config:
        save_when: always

    - name: reload device
      ansible.netcommon.cli_command: 
        command: reload
        prompt: 
          - confirm
        answer: 
          - y

    - name: reset the connection 
      meta: reset_connection

    - name: wait for network device to come back up
      wait_for_connection:
        delay: 15