---
- name: Test playbook
  hosts: RTR1
  gather_facts: False
  tasks:
    # - name: delete all vrfs besides MGMT
    #   cisco.ios.ios_vrf:
    #     vrfs:
    #     - MGMT
    #     purge: yes

    - name: configure ipv4 L3 interfaces that are not sub interfaces
      cisco.ios.ios_l3_interfaces:
        config:
        - name: "Tunnel0"
          ipv4:
          - address: "100.100.100.1/30"
      # loop: "{{ interfaces }}"
      # loop_control:
      #   label: "{{ item.name }}"
      # when: "not item.sub_int and item.ipv4 is defined and 'Loopback' not in item.name"