- name: configure dhcp pools
  cisco.ios.ios_config:
    lines:
    - network {{ item.network | ansible.netcommon.ipaddr('network') }} {{ item.network | ansible.netcommon.ipaddr('netmask') }}
    - default-router {{ item.network | ansible.netcommon.ipaddr('next_usable') }}
    parents: ip dhcp pool {{ item.name }}
  loop: "{{ dhcp_pools }}"
  loop_control:
    label: "DHCP POOL {{ item.name }}"
  when: dhcp_pools is defined