- name: delete named standard acls
  cisco.ios.ios_config:
    lines:
    - no ip access-list standard {{ item.name }}
  loop: "{{ destroy.acl.named.standard }}"
  when: destroy.acl.named.standard is defined

- name: delete named IPv6 prefix lists
  cisco.ios.ios_config:
    lines:
    - no ipv6 prefix-list {{ item.name }}
  loop: "{{ destroy.prefix_lists.ipv6.named }}"
  when: destroy.prefix_lists.ipv6.named is defined