- name: delete eigrp process
  cisco.ios.ios_config:
    lines:
    - no router eigrp {{ destroy.eigrp.as }}
  when: destroy.eigrp.as is defined

- name: delete classic IPv6 eigrp process
  cisco.ios.ios_config:
    lines:
    - no ipv6 router eigrp {{ destroy.eigrp.ipv6.as }}
  when: destroy.eigrp.ipv6.as is defined

- name: Delete all OSPF processes
  cisco.ios.ios_ospfv2:
    state: deleted