- name: delete sub interfaces
  cisco.ios.ios_config:
    lines:
    - no interface {{ item.name }}
  loop: "{{ sub_interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when: sub_interfaces is defined

- name: delete vlan interfaces
  cisco.ios.ios_config:
    lines:
    - no interface {{ item.name }}
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when:  "'vlan' in item.name"

- name: delete loopbacks
  cisco.ios.ios_config:
    lines:
    - no interface {{ item.name }}
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when:  "'Loopback' in item.name"

- name: delete tunnel interfaces
  cisco.ios.ios_config:
    lines:
    - no interface {{ item.name }}
  loop: "{{ tunnel_interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when: tunnel_interfaces is defined

- name: default interfaces
  cisco.ios.ios_config:
    lines:
    - default interface {{ item.name }}
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when: "interfaces is defined and 'Loopback' not in item.name and 'vlan' not in item.name"