# Getting error on this task when executed on switches
# May have to manually delete ACL from switches
- name: delete all ACLs
  cisco.ios.ios_acls:
    state: deleted
  when: "'routers' in group_names"
  ignore_errors: yes

- name: delete named IPv4 prefix lists
  cisco.ios.ios_config:
    lines:
    - no ip prefix-list {{ item.name }}
  loop: "{{ destroy.prefix_lists.ipv4.named }}"
  when: destroy.prefix_lists.ipv4.named is defined

- name: delete named IPv6 prefix lists
  cisco.ios.ios_config:
    lines:
    - no ipv6 prefix-list {{ item.name }}
  loop: "{{ destroy.prefix_lists.ipv6.named }}"
  when: destroy.prefix_lists.ipv6.named is defined

- name: delete bgp as-path acl
  cisco.ios.ios_config:
    lines:
    - no ip as-path access-list {{ item }}
  loop: "{{ destroy.acl.as_path }}"
  when: destroy.acl.as_path is defined

- name: delete bgp community new format
  cisco.ios.ios_config:
    lines:
    - no ip bgp-community new-format

- name: delete numbered community-list
  cisco.ios.ios_config:
    lines:
    - no ip community-list {{ item }}
  loop: "{{ destroy.community_list.numbered }}"
  when: destroy.community_list.numbered is defined