- name: delete eigrp process
  cisco.ios.ios_config:
    lines:
    - no router eigrp {{ item }}
  when: destroy.eigrp.as is defined
  loop: "{{ destroy.eigrp.as }}"

- name: delete classic IPv6 eigrp process
  cisco.ios.ios_config:
    lines:
    - no ipv6 router eigrp {{ item }}
  when: destroy.eigrp.ipv6.as is defined
  loop: "{{ destroy.eigrp.ipv6.as }}"

- name: delete all OSPFv2 processes
  cisco.ios.ios_ospfv2:
    state: deleted
  ignore_errors: yes

- name: delete all OSPFv3 processes
  cisco.ios.ios_ospfv3:
    state: deleted
  ignore_errors: yes

- name: delete bgp
  cisco.ios.ios_bgp:
    config:
      bgp_as: "{{ destroy.bgp.as }}"
    operation: delete
  when: destroy.bgp.as is defined