- name: configure ipv4 static routes
  cisco.ios.ios_config:
    lines:
    - ip route {{ item.dest | ansible.netcommon.ipaddr('network') }} {{ item.dest | ansible.netcommon.ipaddr('netmask') }} {{ item.next_hop_interface | default() }} {{ item.next_hop_address | default() }}
  loop: "{{ static_routes_ipv4 }}"
  loop_control:
    label: "Static route to {{ item.dest }}"
  when: static_routes_ipv4 is defined

# - name: Configure ipv4 static routes
#   cisco.ios.ios_static_routes:
#     config:
#     - address_families:
#       - afi: ipv4
#         routes:
#         - dest: "{{ item.dest }}"
#           next_hops:
#           - interface: "{{ item.next_hop_interface | default(omit) }}"
#             forward_router_address: "{{ item.next_hop_address | default(omit) }}"
#   loop: "{{ static_routes_ipv4 }}"
#   loop_control:
#     label: "Static route to {{ item.dest }}"
#   when: static_routes_ipv4 is defined

# Temp rempval of static routes using this module, ran into some issues. Possible bug.

# - name: Configure ipv6 static routes
#   cisco.ios.ios_static_routes:
#     config:
#     - address_families:
#       - afi: ipv6
#         routes:
#         - dest: "{{ item.dest }}"
#           next_hops:
#           - interface: "{{ item.next_hop_interface | default(omit) }}"
#             forward_router_address: "{{ item.next_hop_address | default(omit) }}"
#   loop: "{{ static_routes_ipv6 }}"
#   loop_control:
#     label: "Static route to {{ item.dest }}"
#   when: static_routes_ipv6 is defined

- name: configure ipv6 static routes
  cisco.ios.ios_config:
    lines:
    - ipv6 route {{ item.dest }} {{ item.next_hop_interface | default() }} {{ item.next_hop_address | default() }}
  loop: "{{ static_routes_ipv6 }}"
  loop_control:
    label: "Static route to {{ item.dest }}"
  when: static_routes_ipv6 is defined