- name: configure access ports
  cisco.ios.ios_config:
    lines:
    - switchport mode access
    - switchport access vlan {{ item.access_vlan }}
    - spanning-tree portfast
    parents: interface {{ item.name }}
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when: "item.mode is defined and item.mode == 'access'"

- name: configure trunk interfaces
  cisco.ios.ios_l2_interfaces:
    config:
    - name: "{{ item.name }}"
      mode: trunk
      trunk:
        encapsulation: dot1q
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when: "item.mode is defined and item.mode == 'trunk'"

- name: enable ip routing on switches
  cisco.ios.ios_config:
    lines: ip routing

- name: configure layer 3 switchports
  cisco.ios.ios_config:
    lines:
    - no switchport
    - ip address {{ item.ip_address | ansible.netcommon.ipaddr('address') }} {{ item.ip_address | ansible.netcommon.ipaddr('netmask') }}
    parents: interface {{ item.name }}
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when:  "item.mode is defined and item.mode == 'l3'"

- name: configure loopbacks
  cisco.ios.ios_config:
    lines:
    - ip address {{ item.ip_address | ansible.netcommon.ipaddr('address') }} {{ item.ip_address | ansible.netcommon.ipaddr('netmask') }}
    parents: interface {{ item.name }}
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.name }}"
  when:  "'Loopback' in item.name"