- name: save config before reload
  cisco.ios.ios_config:
    save_when: always

- name: reload device
  ansible.netcommon.cli_command: 
    command: reload
    prompt: 
      - confirm
    answer: 
      - y

- name: reset the connection 
  meta: reset_connection

- name: wait for network device to come back up
  wait_for_connection:
    delay: 15